#!/bin/bash

if [ -z $1 ]; then
  echo "WARNING: No build path supplied!";
else
	echo "";
	echo "#################################";
	echo "### Setting up environment... ###";
	echo "#################################";
	echo "";
	source build/envsetup.sh
	echo "";
	echo "##############################";
	echo "### Lunching option 1...   ###";
	echo "##############################";
	echo "";
	lunch 1
	echo "";
	echo "####################################";
	echo "### Building $1 ... ###";
	echo "####################################";
	echo "";
	mmm -j32 $1
	echo "";
	echo "##############################";
	echo "### Building system.img... ###";
	echo "##############################";
	echo "";
	make -j32 snod
fi

#echo "Copying Android 2.3 images to windows workspace...";
#cp out/target/product/generic/*.img /mnt/hgfs/workspace/androidroms/android-2.3

